name: Matrix Demo
on: push
jobs:
  build:
    continue-on-error: true # we added this line to continue the workflow even if a job fails
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        operating-system: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
